[2023-08-07T10:46:51.311Z] undefined [31merror[39m: uncaughtException: password authentication failed for user "username"
error: password authentication failed for user "username"
    at Parser.parseErrorMessage (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/sneha/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2023-08-07T10:47:29.931Z] undefined [31merror[39m: uncaughtException: password authentication failed for user "username"
error: password authentication failed for user "username"
    at Parser.parseErrorMessage (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/sneha/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2023-08-07T10:48:43.430Z] undefined [31merror[39m: uncaughtException: password authentication failed for user "username"
error: password authentication failed for user "username"
    at Parser.parseErrorMessage (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/sneha/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2023-08-07T11:00:32.020Z] undefined [31merror[39m: uncaughtException: password authentication failed for user "username"
error: password authentication failed for user "username"
    at Parser.parseErrorMessage (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/sneha/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2023-08-07T11:05:58.428Z] undefined [31merror[39m: uncaughtException: password authentication failed for user "username"
error: password authentication failed for user "username"
    at Parser.parseErrorMessage (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/sneha/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2023-08-07T11:10:14.947Z] undefined [31merror[39m: uncaughtException: password authentication failed for user "username"
error: password authentication failed for user "username"
    at Parser.parseErrorMessage (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/sneha/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2023-08-07T11:11:39.920Z] undefined [31merror[39m: uncaughtException: password authentication failed for user "username"
error: password authentication failed for user "username"
    at Parser.parseErrorMessage (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/sneha/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2023-08-07T11:12:37.278Z] undefined [31merror[39m: uncaughtException: password authentication failed for user "username"
error: password authentication failed for user "username"
    at Parser.parseErrorMessage (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/sneha/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2023-08-07T11:13:55.471Z] undefined [31merror[39m: uncaughtException: password authentication failed for user "username"
error: password authentication failed for user "username"
    at Parser.parseErrorMessage (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/sneha/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2023-08-07T11:14:53.711Z] undefined [31merror[39m: uncaughtException: password authentication failed for user "username"
error: password authentication failed for user "username"
    at Parser.parseErrorMessage (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/sneha/backend/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/sneha/backend/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2023-08-16T09:37:35.051Z] undefined [31merror[39m: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at Server.listen (node:net:1887:7)
    at Function.listen (/home/sneha/backend/node_modules/express/lib/application.js:635:24)
    at /home/sneha/backend/dist/src/app.js:61:16
    at Generator.next (<anonymous>)
    at fulfilled (/home/sneha/backend/dist/src/app.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-08-16T10:03:33.767Z] undefined [31merror[39m: uncaughtException: listen EADDRINUSE: address already in use :::3000
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1751:16)
    at listenInCluster (node:net:1799:12)
    at Server.listen (node:net:1887:7)
    at Function.listen (/home/sneha/backend/node_modules/express/lib/application.js:635:24)
    at /home/sneha/backend/dist/src/app.js:61:16
    at Generator.next (<anonymous>)
    at fulfilled (/home/sneha/backend/dist/src/app.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-08-16T12:09:12.780Z] undefined [31merror[39m: uncaughtException: (0 , cors_1.cors) is not a function
TypeError: (0 , cors_1.cors) is not a function
    at Object.<anonymous> (/home/sneha/backend/dist/src/app.js:50:28)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
[2023-08-17T15:43:57.298Z] undefined [31merror[39m: uncaughtException: Cannot soft-remove, given value must be an entity, instead "null" is given.
MustBeEntityError: Cannot soft-remove, given value must be an entity, instead "null" is given.
    at EntityPersistExecutor.execute (/home/sneha/backend/node_modules/typeorm/persistence/EntityPersistExecutor.js:38:35)
    at EntityManager.softRemove (/home/sneha/backend/node_modules/typeorm/entity-manager/EntityManager.js:241:14)
    at Repository.softRemove (/home/sneha/backend/node_modules/typeorm/repository/Repository.js:88:29)
    at EmployeeRepository.<anonymous> (/home/sneha/backend/dist/src/repository/employee.repository.js:43:44)
    at Generator.next (<anonymous>)
    at fulfilled (/home/sneha/backend/dist/src/repository/employee.repository.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-08-17T15:48:04.704Z] undefined [31merror[39m: uncaughtException: Cannot soft-remove, given value must be an entity, instead "null" is given.
MustBeEntityError: Cannot soft-remove, given value must be an entity, instead "null" is given.
    at EntityPersistExecutor.execute (/home/sneha/backend/node_modules/typeorm/persistence/EntityPersistExecutor.js:38:35)
    at EntityManager.softRemove (/home/sneha/backend/node_modules/typeorm/entity-manager/EntityManager.js:241:14)
    at Repository.softRemove (/home/sneha/backend/node_modules/typeorm/repository/Repository.js:88:29)
    at EmployeeRepository.<anonymous> (/home/sneha/backend/dist/src/repository/employee.repository.js:43:44)
    at Generator.next (<anonymous>)
    at fulfilled (/home/sneha/backend/dist/src/repository/employee.repository.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
